### ISSUE TITLE
[BUG] Extra argument passed to transactions in Stable Cadence Pre-release version

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-cli#1208]
### Problem

When trying to send a transaction with parameters, I consistently get

```sh
❌ Command Error: error parsing transaction arguments: argument count is [n+1], expected [n]
```

### Steps to Reproduce

With the Stable Cadence CLI preview release installed, try the following transaction:

```cadence
transaction(s: String) {
    prepare(signer: &Account) {
        log(s)
    }
}
```

```sh
flow transactions send ./transactions/test_param.cdc hello
```

And it should output:

```sh
❌ Command Error: error parsing transaction arguments: argument count is 2, expected 1
```

Confirm it works without the transaction parameter:

```cadence
transaction {
    prepare(signer: &Account) {
        log("hello")
    }
}
```

```sh
flow transactions send ./transactions/test.cdc
```

And it should succeed.

### Acceptance Criteria

Transactions with and without params should execute.

### Context

Using the preview release to update FLIPs and contracts.

### Machine Info

OS: macOS 13.6 (22G120)
CLI: v1.5.0-stable-cadence.2

**Comment by bjartek** [comment]
This has been fixed in head i belive

**Comment by sisyphusSmiling** [comment]
Just tried with fresh install of `v1.5.0-stable-cadence.2` and still experiencing the issue.

**Comment by turbolent** [comment]
@SupunS Is it possible that the latest Stable Cadence release, `v1.5.0-stable-cadence.2`, does not yet have the Flow CLI `master` code which includes #1179 and #1182? Could you please merge `master` into the Stablwe Cadence feature branch and create a new preview build?

**Comment by bjartek** [comment]
I took a stab at this @turbolent @SupunS

**Comment by SupunS** [comment]
Merging the master seems to fix it.

We should probably add some test cases around this. Didn't see any test in the above two PRs (#1179 and #1182) either.
